# Site settings
title: SUSE Live Documentation
email: jcayouette@suse.com
description: 'Live documentation publisher/site for SUSE products.
Enterprise and development documentation automated via travisci and updated within minutes.
Product docs are stored within their own documentation repositories as .adoc sources (asciidoctor)
and are picked up by travisci on an accepted pull request for building and deployment to this publishing repo.
Content is then published to a single GitHub gh-pages branch.'

url: "https://localhost:4000" # Base hostname & protocol for the Site
baseurl: "" # the subpath for your site, example /docs
gh_url: "https://github.com/jcayouette/suse-publisher2"

liquid:
  error_mode: strict

collections:
  docs:
    permalink: ":collection/:path/"
    output: true
  posts:
    permalink: "news/:year/:month/:day/:title/"
    output: true

defaults:
  -
    scope:
      path: _docs
      type: docs
      values:
        layout: docs
  -
    scope:
      path: _posts
      type: posts
      values:
        layout: news

# TODO Add to collections at a later time.
# SUSE CaaS Platform
#  caas-platform:
#    output: true

# SUSE Cloud Application Platform
#  cloud-app-platform:
#    output: true

# Openstack Cloud
#  openstack-cloud:
#    output: true

# Enterprise Storage
#  storage:
#    output: true

# SLES Server
#  sles:
#    output: true

# SLES Desktop
#  sles-desktop:
#    output: true

# SLES High Availability Extension
#  sles-ha:
#    output: true

# SLES Point of Service
#  sles-pos:
#    output: true

# SLES Point of Service Image Server
#  sles-pos-is:
#    output: true

# Real Time Extensions
#  sles-rt:
#    output: true

# SAP Applications
#  sles-sap:
#    output: true
